// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.getJSON('/mock_results', function(data) {
      var groupItem, html, item, key, template, testcase, _i, _j, _len, _len1, _ref, _results;
      template = Handlebars.compile($("#card-template").html());
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        item = data[_i];
        item.testsuite.$.pass = item.testsuite.$.tests - item.testsuite.$.failures;
        _ref = item.testsuite.testcase;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          testcase = _ref[_j];
          testcase.status = testcase.failure ? 'failed' : 'pass';
        }
        item.group = (function() {
          var _ref1, _results1;
          _ref1 = _.groupBy(item.testsuite.testcase, function(testcase) {
            return testcase.$.classname;
          });
          _results1 = [];
          for (key in _ref1) {
            groupItem = _ref1[key];
            _results1.push({
              name: key,
              testcase: groupItem
            });
          }
          return _results1;
        })();
        html = template(item);
        _results.push($('.card-list-container').append(html));
      }
      return _results;
    });
  });

}).call(this);
